/**
 * Web Preview Mock Data — Provides sample data when running in browser
 * so stakeholders can see a populated UI without Electron/SQLite.
 */

import type { Conversation, TranscriptSegment, AuthUser, Task, Companion } from '../../shared/types';
import type { Highlight } from '../services/conversationService';

export const MOCK_USER: AuthUser = {
  id: 'preview-user',
  displayName: 'Ahmed Al Mansouri',
  email: 'ahmed.almansouri@dge.gov.ae',
  tenantId: 'preview-tenant',
  accessToken: '',
};

export const MOCK_CONVERSATIONS: (Conversation & { segmentCount: number })[] = [
  {
    id: 'conv-1',
    title: 'Q4 Budget Review with Finance Team',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    duration: 2340,
    companionId: 'finance-advisor',
    tags: ['budget', 'Q4', 'finance'],
    speakerCount: 4,
    audioPath: null,
    status: 'complete',
    segmentCount: 47,
  },
  {
    id: 'conv-2',
    title: 'Digital Transformation Strategy Session',
    createdAt: new Date(Date.now() - 26 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 26 * 3600000).toISOString(),
    duration: 3600,
    companionId: 'strategic-advisor',
    tags: ['strategy', 'digital', 'transformation'],
    speakerCount: 6,
    audioPath: null,
    status: 'complete',
    segmentCount: 82,
  },
  {
    id: 'conv-3',
    title: 'Weekly Team Standup — AI Factory',
    createdAt: new Date(Date.now() - 50 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 3600000).toISOString(),
    duration: 1200,
    companionId: 'meeting-coach',
    tags: ['standup', 'AI'],
    speakerCount: 8,
    audioPath: null,
    status: 'complete',
    segmentCount: 34,
  },
  {
    id: 'conv-4',
    title: 'GovAI Branding Proposal Review',
    createdAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    duration: 1800,
    companionId: null,
    tags: ['branding', 'proposal'],
    speakerCount: 3,
    audioPath: null,
    status: 'complete',
    segmentCount: 29,
  },
  {
    id: 'conv-5',
    title: 'Protocol Briefing — Diplomatic Reception',
    createdAt: new Date(Date.now() - 168 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 168 * 3600000).toISOString(),
    duration: 900,
    companionId: 'protocol-coach',
    tags: ['protocol', 'diplomatic'],
    speakerCount: 2,
    audioPath: null,
    status: 'complete',
    segmentCount: 18,
  },
];

export const MOCK_SEGMENTS: TranscriptSegment[] = [
  {
    id: 'seg-1',
    conversationId: 'conv-1',
    speakerId: 'spk-1',
    speakerLabel: 'Ahmed Al Mansouri',
    text: 'Let\'s begin the Q4 budget review. I\'d like everyone to share their department updates.',
    startTime: 0,
    endTime: 8,
    language: 'en',
    confidence: 0.95,
  },
  {
    id: 'seg-2',
    conversationId: 'conv-1',
    speakerId: 'spk-2',
    speakerLabel: 'Fatima Al Hashimi',
    text: 'بالنسبة لقسم التقنية، نحن ضمن الميزانية المحددة. تم صرف ٨٥٪ من الميزانية المعتمدة حتى الآن.',
    startTime: 9,
    endTime: 18,
    language: 'ar',
    confidence: 0.92,
  },
  {
    id: 'seg-3',
    conversationId: 'conv-1',
    speakerId: 'spk-2',
    speakerLabel: 'Fatima Al Hashimi',
    text: 'We still have the cloud infrastructure upgrade pending, which accounts for the remaining 15%.',
    startTime: 19,
    endTime: 26,
    language: 'en',
    confidence: 0.88,
  },
  {
    id: 'seg-4',
    conversationId: 'conv-1',
    speakerId: 'spk-3',
    speakerLabel: 'Omar Al Suwaidi',
    text: 'The HR department is slightly over budget due to the new recruitment platform. We need an additional 50,000 AED.',
    startTime: 27,
    endTime: 36,
    language: 'en',
    confidence: 0.91,
  },
  {
    id: 'seg-5',
    conversationId: 'conv-1',
    speakerId: 'spk-1',
    speakerLabel: 'Ahmed Al Mansouri',
    text: 'هل يمكننا تغطية ذلك من الميزانية الاحتياطية؟',
    startTime: 37,
    endTime: 42,
    language: 'ar',
    confidence: 0.94,
  },
  {
    id: 'seg-6',
    conversationId: 'conv-1',
    speakerId: 'spk-4',
    speakerLabel: 'Sara Al Ketbi',
    text: 'Yes, we have sufficient reserves. I can process the reallocation this week.',
    startTime: 43,
    endTime: 50,
    language: 'en',
    confidence: 0.96,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Process budget reallocation for HR department',
    description: 'Reallocate 50,000 AED from reserves to cover the new recruitment platform costs.',
    status: 'in_progress',
    priority: 'high',
    ownerId: 'spk-4',
    ownerName: 'Sara Al Ketbi',
    dueDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    sourceConversationId: 'conv-1',
    sourceSegmentId: 'seg-6',
    plannerId: null,
    category: 'my_tasks',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'task-2',
    title: 'Complete cloud infrastructure upgrade',
    description: 'Finalize the remaining 15% of the technology department budget for cloud migration.',
    status: 'todo',
    priority: 'urgent',
    ownerId: 'spk-2',
    ownerName: 'Fatima Al Hashimi',
    dueDate: new Date(Date.now() + 14 * 86400000).toISOString(),
    sourceConversationId: 'conv-1',
    sourceSegmentId: 'seg-3',
    plannerId: null,
    category: 'my_tasks',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Review digital transformation roadmap',
    description: 'Consolidate feedback from all departments and prepare final roadmap for board review.',
    status: 'todo',
    priority: 'medium',
    ownerId: 'spk-1',
    ownerName: 'Ahmed Al Mansouri',
    dueDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    sourceConversationId: 'conv-2',
    sourceSegmentId: null,
    plannerId: null,
    category: 'my_tasks',
    createdAt: new Date(Date.now() - 26 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 26 * 3600000).toISOString(),
  },
  {
    id: 'task-4',
    title: 'Prepare Q1 budget forecast',
    description: 'Based on Q4 actuals, prepare preliminary Q1 budget projections.',
    status: 'done',
    priority: 'medium',
    ownerId: 'spk-4',
    ownerName: 'Sara Al Ketbi',
    dueDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    sourceConversationId: 'conv-1',
    sourceSegmentId: null,
    plannerId: null,
    category: 'my_tasks',
    createdAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'task-5',
    title: 'Update recruitment platform vendor contract',
    description: 'Negotiate and finalize the annual contract renewal with the platform vendor.',
    status: 'in_progress',
    priority: 'high',
    ownerId: 'spk-3',
    ownerName: 'Omar Al Suwaidi',
    dueDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    sourceConversationId: 'conv-1',
    sourceSegmentId: 'seg-4',
    plannerId: null,
    category: 'delegated',
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'task-6',
    title: 'Schedule follow-up meeting with IT team',
    description: 'Coordinate with IT to discuss cloud migration timeline and dependencies.',
    status: 'todo',
    priority: 'low',
    ownerId: 'spk-2',
    ownerName: 'Fatima Al Hashimi',
    dueDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    sourceConversationId: 'conv-2',
    sourceSegmentId: null,
    plannerId: null,
    category: 'delegated',
    createdAt: new Date(Date.now() - 26 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 26 * 3600000).toISOString(),
  },
  {
    id: 'task-7',
    title: 'Diplomatic reception venue confirmation',
    description: 'Confirm venue booking and catering arrangements for the upcoming reception.',
    status: 'in_progress',
    priority: 'high',
    ownerId: null,
    ownerName: 'Protocol Office',
    dueDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    sourceConversationId: 'conv-5',
    sourceSegmentId: null,
    plannerId: null,
    category: 'waiting_on',
    createdAt: new Date(Date.now() - 168 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
];

export const MOCK_COMPANIONS: Companion[] = [
  {
    id: 'meeting-coach',
    name: 'Meeting Excellence Coach',
    nameAr: 'مدرب التميز في الاجتماعات',
    description: 'Analyzes meetings for effectiveness, tracks action items, and provides feedback on meeting dynamics.',
    descriptionAr: 'يحلل الاجتماعات من حيث الفعالية، ويتتبع بنود العمل، ويقدم ملاحظات حول ديناميكيات الاجتماع.',
    systemPrompt: 'You are a meeting effectiveness coach for Abu Dhabi Government professionals. Analyze conversations for: clarity of objectives, action item tracking, time management, decision-making quality, and participant engagement. Provide constructive feedback in both Arabic and English.',
    icon: 'sparkles',
    isBuiltIn: true,
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'strategic-advisor',
    name: 'Strategic Advisor',
    nameAr: 'المستشار الاستراتيجي',
    description: 'Provides strategic analysis, identifies risks and opportunities, and aligns discussions with organizational goals.',
    descriptionAr: 'يقدم تحليلاً استراتيجياً، ويحدد المخاطر والفرص، ويواءم النقاشات مع الأهداف المؤسسية.',
    systemPrompt: 'You are a strategic advisor for government leaders. Analyze conversations for strategic implications, identify risks, suggest alignments with Abu Dhabi Vision 2030, and provide recommendations for policy decisions.',
    icon: 'brain',
    isBuiltIn: true,
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'personal-assistant',
    name: 'Personal Assistant',
    nameAr: 'المساعد الشخصي',
    description: 'Manages tasks, organizes daily schedules, drafts responses, and handles routine administrative work.',
    descriptionAr: 'يدير المهام، وينظم الجداول اليومية، ويصيغ الردود، ويتعامل مع الأعمال الإدارية الروتينية.',
    systemPrompt: 'You are a personal productivity assistant. Help organize tasks, prioritize work, draft professional communications, and manage schedules efficiently.',
    icon: 'bot',
    isBuiltIn: true,
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'finance-advisor',
    name: 'Finance Advisor',
    nameAr: 'المستشار المالي',
    description: 'Tracks budget discussions, analyzes financial data mentioned in meetings, and monitors spending patterns.',
    descriptionAr: 'يتتبع نقاشات الميزانية، ويحلل البيانات المالية المذكورة في الاجتماعات، ويراقب أنماط الإنفاق.',
    systemPrompt: 'You are a government finance advisor. Track budget allocations, analyze financial discussions, flag spending concerns, and provide insights on fiscal responsibility and compliance.',
    icon: 'dollar-sign',
    isBuiltIn: true,
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'protocol-coach',
    name: 'Protocol & Etiquette Coach',
    nameAr: 'مدرب البروتوكول والإتيكيت',
    description: 'Guides on government protocol, diplomatic etiquette, and formal communication standards.',
    descriptionAr: 'يرشد في بروتوكول الحكومة، والإتيكيت الدبلوماسي، ومعايير التواصل الرسمي.',
    systemPrompt: 'You are a protocol and etiquette advisor for government officials. Guide on proper diplomatic protocols, formal communication, cultural sensitivity, and official ceremony procedures.',
    icon: 'crown',
    isBuiltIn: true,
    isActive: false,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
];

export const MOCK_HIGHLIGHTS: Highlight[] = [
  {
    id: 'hl-1',
    conversationId: 'conv-1',
    type: 'key_point',
    text: 'Technology department is at 85% budget utilization with cloud upgrade pending.',
    sourceSegmentId: 'seg-2',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hl-2',
    conversationId: 'conv-1',
    type: 'decision',
    text: 'Approved reallocation of 50,000 AED from reserves for HR recruitment platform.',
    sourceSegmentId: 'seg-6',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hl-3',
    conversationId: 'conv-1',
    type: 'action_item',
    text: 'Sara Al Ketbi to process budget reallocation for HR department this week.',
    sourceSegmentId: 'seg-6',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hl-4',
    conversationId: 'conv-1',
    type: 'commitment',
    text: 'Cloud infrastructure upgrade to be completed within Q4 timeline.',
    sourceSegmentId: 'seg-3',
    createdAt: new Date().toISOString(),
  },
];
