/**
 * Web Preview Mock Data — Provides sample data when running in browser
 * so stakeholders can see a populated UI without Electron/SQLite.
 */

import type { Conversation, TranscriptSegment, AuthUser } from '../../shared/types';
import type { Highlight } from '../services/conversationService';

export const MOCK_USER: AuthUser = {
  id: 'preview-user',
  displayName: 'Ahmed Al Mansouri',
  email: 'ahmed.almansouri@dge.gov.ae',
  tenantId: 'preview-tenant',
  accessToken: '',
};

export const MOCK_CONVERSATIONS: (Conversation & { segmentCount: number })[] = [
  {
    id: 'conv-1',
    title: 'Q4 Budget Review with Finance Team',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    duration: 2340,
    companionId: 'finance-advisor',
    tags: ['budget', 'Q4', 'finance'],
    speakerCount: 4,
    audioPath: null,
    status: 'complete',
    segmentCount: 47,
  },
  {
    id: 'conv-2',
    title: 'Digital Transformation Strategy Session',
    createdAt: new Date(Date.now() - 26 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 26 * 3600000).toISOString(),
    duration: 3600,
    companionId: 'strategic-advisor',
    tags: ['strategy', 'digital', 'transformation'],
    speakerCount: 6,
    audioPath: null,
    status: 'complete',
    segmentCount: 82,
  },
  {
    id: 'conv-3',
    title: 'Weekly Team Standup — AI Factory',
    createdAt: new Date(Date.now() - 50 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 3600000).toISOString(),
    duration: 1200,
    companionId: 'meeting-coach',
    tags: ['standup', 'AI'],
    speakerCount: 8,
    audioPath: null,
    status: 'complete',
    segmentCount: 34,
  },
  {
    id: 'conv-4',
    title: 'GovAI Branding Proposal Review',
    createdAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    duration: 1800,
    companionId: null,
    tags: ['branding', 'proposal'],
    speakerCount: 3,
    audioPath: null,
    status: 'complete',
    segmentCount: 29,
  },
  {
    id: 'conv-5',
    title: 'Protocol Briefing — Diplomatic Reception',
    createdAt: new Date(Date.now() - 168 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 168 * 3600000).toISOString(),
    duration: 900,
    companionId: 'protocol-coach',
    tags: ['protocol', 'diplomatic'],
    speakerCount: 2,
    audioPath: null,
    status: 'complete',
    segmentCount: 18,
  },
];

export const MOCK_SEGMENTS: TranscriptSegment[] = [
  {
    id: 'seg-1',
    conversationId: 'conv-1',
    speakerId: 'spk-1',
    speakerLabel: 'Ahmed Al Mansouri',
    text: 'Let\'s begin the Q4 budget review. I\'d like everyone to share their department updates.',
    startTime: 0,
    endTime: 8,
    language: 'en',
    confidence: 0.95,
  },
  {
    id: 'seg-2',
    conversationId: 'conv-1',
    speakerId: 'spk-2',
    speakerLabel: 'Fatima Al Hashimi',
    text: 'بالنسبة لقسم التقنية، نحن ضمن الميزانية المحددة. تم صرف ٨٥٪ من الميزانية المعتمدة حتى الآن.',
    startTime: 9,
    endTime: 18,
    language: 'ar',
    confidence: 0.92,
  },
  {
    id: 'seg-3',
    conversationId: 'conv-1',
    speakerId: 'spk-2',
    speakerLabel: 'Fatima Al Hashimi',
    text: 'We still have the cloud infrastructure upgrade pending, which accounts for the remaining 15%.',
    startTime: 19,
    endTime: 26,
    language: 'en',
    confidence: 0.88,
  },
  {
    id: 'seg-4',
    conversationId: 'conv-1',
    speakerId: 'spk-3',
    speakerLabel: 'Omar Al Suwaidi',
    text: 'The HR department is slightly over budget due to the new recruitment platform. We need an additional 50,000 AED.',
    startTime: 27,
    endTime: 36,
    language: 'en',
    confidence: 0.91,
  },
  {
    id: 'seg-5',
    conversationId: 'conv-1',
    speakerId: 'spk-1',
    speakerLabel: 'Ahmed Al Mansouri',
    text: 'هل يمكننا تغطية ذلك من الميزانية الاحتياطية؟',
    startTime: 37,
    endTime: 42,
    language: 'ar',
    confidence: 0.94,
  },
  {
    id: 'seg-6',
    conversationId: 'conv-1',
    speakerId: 'spk-4',
    speakerLabel: 'Sara Al Ketbi',
    text: 'Yes, we have sufficient reserves. I can process the reallocation this week.',
    startTime: 43,
    endTime: 50,
    language: 'en',
    confidence: 0.96,
  },
];

export const MOCK_HIGHLIGHTS: Highlight[] = [
  {
    id: 'hl-1',
    conversationId: 'conv-1',
    type: 'key_point',
    text: 'Technology department is at 85% budget utilization with cloud upgrade pending.',
    sourceSegmentId: 'seg-2',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hl-2',
    conversationId: 'conv-1',
    type: 'decision',
    text: 'Approved reallocation of 50,000 AED from reserves for HR recruitment platform.',
    sourceSegmentId: 'seg-6',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hl-3',
    conversationId: 'conv-1',
    type: 'action_item',
    text: 'Sara Al Ketbi to process budget reallocation for HR department this week.',
    sourceSegmentId: 'seg-6',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hl-4',
    conversationId: 'conv-1',
    type: 'commitment',
    text: 'Cloud infrastructure upgrade to be completed within Q4 timeline.',
    sourceSegmentId: 'seg-3',
    createdAt: new Date().toISOString(),
  },
];
